import { ConvexError, v } from "convex/values";
import {
  internalMutation,
  internalQuery,
  mutation,
  query,
} from "./_generated/server";
import { requireAccount } from "./lib/auth";

// Account for the current session, minus widgetSecret (app surface).
export const current = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    let account;
    try {
      account = await requireAccount(ctx, sessionToken);
    } catch {
      return null;
    }
    const { widgetSecret: _secret, ...safe } = account;
    return safe;
  },
});

// Full account doc for actions (internal only — includes widgetSecret).
export const getForSession = internalQuery({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    return requireAccount(ctx, sessionToken);
  },
});

export const getById = internalQuery({
  args: { id: v.id("accounts") },
  handler: async (ctx, { id }) => ctx.db.get(id),
});

// Widget secret for the install/settings pages (never in accounts.current).
export const widgetSecret = query({
  args: { sessionToken: v.string() },
  handler: async (ctx, { sessionToken }) => {
    const account = await requireAccount(ctx, sessionToken);
    return account.widgetSecret;
  },
});

// Offer defaults, kill switch, secret rotation (FR-014).
export const updateSettings = mutation({
  args: {
    sessionToken: v.string(),
    pauseDays: v.optional(v.number()),
    couponId: v.optional(v.union(v.string(), v.null())),
    killSwitch: v.optional(v.boolean()),
    rotateSecret: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const account = await requireAccount(ctx, args.sessionToken);
    if (args.pauseDays !== undefined) {
      if (![7, 14, 30, 60].includes(args.pauseDays)) {
        throw new ConvexError({ code: "invalid_pause_days" });
      }
      await ctx.db.patch(account._id, {
        offerConfig: { ...account.offerConfig, pauseDays: args.pauseDays },
      });
    }
    if (args.couponId !== undefined) {
      await ctx.db.patch(account._id, {
        offerConfig: {
          pauseDays:
            args.pauseDays ?? account.offerConfig.pauseDays,
          couponId: args.couponId === null ? undefined : args.couponId,
        },
      });
    }
    if (args.killSwitch !== undefined && account.widgetStatus !== "revoked") {
      await ctx.db.patch(account._id, {
        widgetStatus: args.killSwitch
          ? "killed"
          : account.lastHeartbeatAt
            ? "live"
            : "not_installed",
      });
    }
    if (args.rotateSecret) {
      const buf = new Uint8Array(32);
      crypto.getRandomValues(buf);
      await ctx.db.patch(account._id, {
        widgetSecret: Array.from(buf, (b) =>
          b.toString(16).padStart(2, "0")
        ).join(""),
      });
    }
    return null;
  },
});

// OAuth upsert. Keys are generated by the calling action (mutations are
// deterministic); on reconnect existing keys are preserved.
export const upsertFromOAuth = internalMutation({
  args: {
    stripeAccountId: v.string(),
    businessName: v.string(),
    logoUrl: v.optional(v.string()),
    brandColor: v.optional(v.string()),
    email: v.optional(v.string()),
    newPublicKey: v.string(),
    newWidgetSecret: v.string(),
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("accounts")
      .withIndex("by_stripe_account", (q) =>
        q.eq("stripeAccountId", args.stripeAccountId)
      )
      .unique();
    if (existing) {
      // Reconnect = sign-in. Refresh branding, never regenerate keys.
      await ctx.db.patch(existing._id, {
        businessName: args.businessName,
        logoUrl: args.logoUrl,
        brandColor: args.brandColor,
        email: args.email,
        // un-revoke on reconnect
        widgetStatus:
          existing.widgetStatus === "revoked"
            ? "not_installed"
            : existing.widgetStatus,
      });
      return existing._id;
    }
    return ctx.db.insert("accounts", {
      stripeAccountId: args.stripeAccountId,
      businessName: args.businessName,
      logoUrl: args.logoUrl,
      brandColor: args.brandColor,
      email: args.email,
      publicKey: args.newPublicKey,
      widgetSecret: args.newWidgetSecret,
      offerConfig: { pauseDays: 30 },
      widgetStatus: "not_installed",
      createdAt: Date.now(),
    });
  },
});
